apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/productpage
images:
  - name: productpage
    newName: konfidence.common.repositories.cloud.sap/example-app-tests/apps/bookinfo-productpage
    newTag: "v1"
