apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

namespace: bookinfo-dev

images:
  - name: productpage
    newName: konfidence.common.repositories.cloud.sap/example-app-tests/apps/examples-bookinfo-productpage-v1
    newTag: latest
