apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/ratings
images:
  - name: ratings
    newName: konfidence.common.repositories.cloud.sap/example-app-tests/apps/bookinfo-ratings
    newTag: "v2"
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ratings-v1
    patch: |-
      - op: replace
        path: /metadata/labels/version
        value: v2
      - op: replace
        path: /spec/selector/matchLabels/version
        value: v2
      - op: replace
        path: /spec/template/metadata/labels/version
        value: v2
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "v2"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DB_TYPE
          value: "mysql"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MYSQL_DB_HOST
          value: "mysqldb"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MYSQL_DB_PORT
          value: "3306"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MYSQL_DB_USER
          value: "root"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MYSQL_DB_PASSWORD
          value: "password"
  - target:
      version: v1
      kind: Service
      name: ratings
    patch: |-
      - op: replace
        path: /spec/selector/version
        value: v2
