apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: reviews
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: ENABLE_RATINGS
              value: "false"
      imagePullSecrets:
        - name: konfidence-common-repositories-cloud-sap
