# ${REGISTRY} is replaced at push time.
apiVersion: konfidence.cloud/v1alpha1
kind: StageConfiguration
metadata:
  name: example-app
  namespace: example-landscape
spec:
  name: example-app
  targetNamespace: example-landscape
  vector: oci::https://${REGISTRY}//github.com/konfidence-project/example-app/vector:main
