# ${REGISTRY} is replaced at push time.
apiVersion: konfidence.cloud/v1alpha1
kind: VectorTemplate
metadata:
  name: example-app
  namespace: example-landscape
spec:
  uploadTarget: oci::https://${REGISTRY}//github.com/konfidence-project/example-app/vector:main

  components:
    - name: oci::https://${REGISTRY}//github.com/konfidence-project/example-app/candidates:v0.1.0
    - name: oci::https://${REGISTRY}//github.com/konfidence-project/example-app/interviews:v0.1.0

  vectorConfig:
    features:
      allow-video-slots: false
      enable-candidate-notes: false
