apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: candidates
  newName: ghcr.io/konfidence-project/candidates
  newTag: v0.1.0
