apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidates
  labels:
    app: candidates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidates
  template:
    metadata:
      labels:
        app: candidates
    spec:
      containers:
        - name: candidates
          image: kind-registry:5000/example-app/candidates:v0.1.0
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: example-app-db-credentials
          env:
            - name: VECTOR_CONFIG_URL
              value: http://vector-data-service
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
