apiVersion: v1
kind: Service
metadata:
  name: candidates
  labels:
    app: candidates
  annotations:
    konfidence.cloud/deployment-result: candidates
spec:
  selector:
    app: candidates
  ports:
    - name: http
      port: 80
      targetPort: http
