apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/reviews
images:
  - name: reviews
    newName: konfidence.common.repositories.cloud.sap/example-app-tests/apps/bookinfo-reviews
    newTag: "v2"
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: reviews-v1
    patch: |-
      - op: replace
        path: /metadata/name
        value: reviews-v2
      - op: replace
        path: /metadata/labels/version
        value: v2
      - op: replace
        path: /spec/selector/matchLabels/version
        value: v2
      - op: replace
        path: /spec/template/metadata/labels/version
        value: v2
      - op: replace # set ENABLE_RATINGS to true
        path: /spec/template/spec/containers/0/env/0/value
        value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STAR_COLOR
          value: black
  - target:
      version: v1
      kind: Service
      name: reviews
    patch: |-
      - op: replace
        path: /spec/selector/version
        value: v2
