apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: productpage
          image: productpage
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: DETAILS_HOSTNAME
              value: details
            - name: REVIEWS_HOSTNAME
              value: reviews
      imagePullSecrets:
        - name: konfidence-common-repositories-cloud-sap
