apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    konfidence.cloud/appname: productpage
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
    version: v1